#                    Copyright (c) 2016-2016
#   Data Intensive Applications and Systems Labaratory (DIAS)
#            Ecole Polytechnique Federale de Lausanne
#
#                      All Rights Reserved.
#
# Permission to use, copy, modify and distribute this software and its
# documentation is hereby granted, provided that both the copyright notice
# and this permission notice appear in all copies of the software, derivative
# works or modified versions, and any portions thereof, and that both notices
# appear in supporting documentation.
#
# This code is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. THE AUTHORS AND ECOLE POLYTECHNIQUE FEDERALE DE LAUSANNE
# DISCLAIM ANY LIABILITY OF ANY KIND FOR ANY DAMAGES WHATSOEVER RESULTING FROM THE
# USE OF THIS SOFTWARE.

version: '2'
# the following environment variables are expected to be available when running
# docker-compose up
# - raw_data_root:      The folder containing the data files (CSV, json,...) on the
#                       swarm node host. Mapped to /datasets WITHIN the containers
# - pg_data_root:       The folder containing the PostgreSQL binary tables on the
#                       swarm node host. Mapped to /data WITHIN the containers

services:

  RawUI:
    image: "hbpmip/postgresraw-ui"
    container_name: "PostgresRAW-UI"
    environment:
     - POSTGRES_HOST
     - POSTGRES_PORT
     - POSTGRES_USER
     - POSTGRES_PASSWORD
     - POSTGRES_DB=db
     #- FED_DATA_SOURCE="harmonized_clinical_data"
     #- LOCAL_DATA_SOURCE="mip_cde_features harmonized_clinical_data"
    volumes:
     - "${raw_data_root}:/datasets:ro"
     - "${pg_data_root}:/data:ro"
    links:
     - "PostgresRAW:db"
